### ISSUE TITLE
st-switch

### ISSUE THREAD

**Issue by ppenalver** [Stratio/egeo#166]
Create st-switch component

**Comment by EvaMGC** [comment]
https://app.zeplin.io/project.html#pid=57b2d594bf84d435234e8c2a&sid=57b2fbf0df57178d3e1056dd

**Comment by EvaMGC** [comment]
https://app.zeplin.io/project.html#pid=57b2d594bf84d435234e8c2a&sid=57b2fbf0df57178d3e1056dd

**Comment by abrahamnavas** [comment]
[UX Definition](https://zpl.io/1kLO3m)
