### ISSUE TITLE
Page Title title should be editable

### ISSUE THREAD

**Issue by acuevas-stratio** [Stratio/egeo#261]
** Please don't delete this template or we'll close your issue **

**I'm submitting a ...**
- [ ] bug report
- [ X ] feature request
- [ ] question

**Define your petition as much as possible**

In Page Title component, 'title' input should be an editable field.

**What is the current behavior?**

Title input can't be edited

**If the current behavior is a bug, please provide the steps to reproduce it**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

UX requirement

**Please tell us about your environment:**

- Egeo version: 2.1.0
- Browser: [all ]

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by pjpenast** [comment]
@abrahamnavas It need UX definition

**Comment by abrahamnavas** [comment]
There you are: [UX Definition](https://zpl.io/Z2uslds)
